trigger: 
- main

pool: 
  vmImage: 'ubuntu-latest'

stages:
- stage: Build_Frontend_Application_Dev
  displayName: 'Build stage for Frontend application'
  variables:
  - group: ory-authorization-dev  
  jobs:
  - job: Build

    steps:

    - task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@5
      displayName: 'Prepare analysis on SonarQube'
      inputs:
        SonarQube: 'SonarQube-service-connection-DF'
        scannerMode: CLI
        configMode: manual
        cliProjectKey: 'DF-Tenant-Portal'
        cliProjectName: 'DF-Tenant-Portal'
    
    - task: SonarSource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@5
      displayName: 'Run Code Analysis'
 
    - task: SonarSource.sonarqube.291ed61f-1ee4-45d3-b1b0-bf822d9095ef.SonarQubePublish@5
      displayName: 'Publish Quality Gate Result'